<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\planningRecette.Domain\planningRecette.Domain.csproj" />
    <ProjectReference Include="..\planningRecette.Infrastructure\planningRecette.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Service\" />
  </ItemGroup>

</Project>
